config/routes.rb
Successpath::Application.routes.draw do
  
  devise_for :members, :controllers => { :registrations => "registrations" }

  scope '/admin' do
    resources :members
  end

  get "pages/home"

  get "pages/contact"

  resources :affirmations

  resources :goals do
    member do
      get 'achieved'
    end
  end

  resources :tasks do
    member do
      get 'achieved'
    end
  end

  resources :users

  root :to => "pages#home"
  

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :achievedate, :date, :duedate, :goal_id, :member_id, :name

  belongs_to :goal
  belongs_to :member

  accepts_nested_attributes_for :goal, :member

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def achieved
    @task = Task.find(params[:id])

    respond_to do |format|
      @task.achievedate = Date.today
      @task.save

      if @task.goal_id.present?
        format.html { redirect_to goal_path(@task.goal_id)}
      else
        format.html {redirect_to tasks_path}
      end
      format.json
    end
  end

  # GET /tasks
  # GET /tasks.json
  def index
    if member_signed_in?
      @opentasks = Task.where("member_id = ? and achievedate is ?", current_member, nil)
      @closedtasks = Task.where("member_id = ? and achievedate is not ?", current_member, nil)
    else
      @opentasks = Task.limit(5)
      @closedtasks = Task.limit(2)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
    if params[:goal].present?
      @goal = Goal.find(params[:goal])
    else
      @goals = Goal.find_all_by_member_id(current_member)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
    if @task.goal_id != nil
      @goal = Goal.find(@task.goal_id)
    end
    @goals = Goal.find_all_by_member_id(current_member)
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_member.tasks.build(params[:task])
    if params[:goal].present?
      @goal = Goal.find(params[:goal])
    else
      @goals = Goal.find_all_by_member_id(current_member)
    end

    respond_to do |format|
      if @task.save
        if @task.goal_id.present?
          format.html { redirect_to goal_path(@task.goal_id) }
        else
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        end
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])
    @goals = Goal.find_all_by_member_id(current_member)

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to tasks_path, notice: 'Task was successfully updated!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      if @task.goal_id.present?
        format.html { redirect_to goal_path(@task.goal_id)}
      else
      format.html { redirect_to tasks_url }
    end
      format.json { head :no_content }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_closedtasktiles.html.erb
<% @closedtasks.each do |task| %>
		<div class="box">
			<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
					<div class="flipper">
					  	<div class="front" style="background:black">
					    <div class="sectiontitle" style="color:white"><%= task.name %></div>
					  </div>
					  <div class="back">
					    <wordbox>
			        		<name><%= task.name %></name><br/>
				        		<description>
				        			<% if task.duedate != nil %>
			        					<%= distance_of_time_in_words(Time.now,task.duedate) %> left to achieve it<br/>
			        				<% end %>
			        				Created <%= distance_of_time_in_words(Time.now,task.created_at) %> ago<br/>
			        				<% if member_signed_in? %>
					        			<% if task.goal_id.present? %>Goal: <%= link_to task.goal.name, goal_path(task.goal_id) %><% end %><br/>
					        				Due Date: <%= task.duedate %><br/>
						        			Achieved Date:<%= task.achievedate %>
						        	<% else %>
						        		<% if task.goal_id.present? %>Associated Goal: <%= task.goal.name %><% end %><br/>
						        		Due Date: <%= task.duedate %><br/>
						        		Achieved Date: <%= task.achievedate %>
						        	<% end %>
					        	</description>
			        	</wordbox>
					  </div>
					</div>
				</div>
	    </div>
	<% end %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>

  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @goal.present? %>
    <%= f.hidden_field :goal_id, :value => @goal.id %>
  <% else %>

  <div class="inputbox">
    <div class="field">
      Associate a Goal (optional)<br />
      <%= collection_select(:task, :goal_id, @goals, :id, :name, {include_blank: 'None'}, :class => 'inputfield') %>
    </div>
    <% end %>
    <div class="field">
      Name the Task<br />
      <%= f.text_field :name, :class => 'inputfield' %>
    </div>
    <div class="field">
      Due Date<br />
      <%= f.text_field :duedate, :class => 'datepicker' %>
    </div>

    <%= f.submit 'Save', :class => 'button-link', :style => 'font-size:1.1em' %> or
        <%= link_to 'Cancel', tasks_path, :class => 'button-link' %> This New Task
  </div>

<% end %>

app/views/tasks/_opentasktiles.html.erb
<% @opentasks.each do |task| %>
		<div class="box">
			<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
					<div class="flipper">
						<% if task.duedate != nil %>
							<% if task.duedate.past? %>
								<div class="front" style="background:red;color:white">
							<% elsif task.duedate == Date.today %>
								<div class="front" style="background:gray;color:white">
							<% elsif task.duedate > Date.today %>
								<div class="front" style="background:green;color:white">
							<% end %>
						<% else %>
					  		<div class="front">
					  	<% end %>
					    <div class="sectiontitle" style="color:white"><%= task.name %></div>
					  </div>
					  <div class="back">
					    <wordbox>
			        		<name><%= task.name %></name><br/>
				        		<description>
				        			<% if task.duedate != nil && task.duedate >= Date.today %>
			        					<%= distance_of_time_in_words(Time.now,task.duedate) %> left to achieve it<br/>
			        				<% elsif task.duedate != nil && task.duedate < Date.today %>
			        					 <%= distance_of_time_in_words(Time.now,task.duedate) %> overdue!<br/>
			        				<% end %>
				        			Created <%= distance_of_time_in_words(Time.now,task.created_at) %> ago<br/>
					        		<% if member_signed_in? %>
			        					<% if task.goal_id.present? %>Goal: <%= link_to task.goal.name, goal_path(task.goal_id) %><% end %><br/>
					        				<%= task.duedate %><br/>
						        			<%= link_to 'Edit', edit_task_path(task) %> | 
						        			<%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %> |
						        			<%= link_to 'Achieved', achieved_task_path(task) %>
						        	<% else %>
						        		<% if task.goal_id.present? %>Associated Goal: <%= task.goal.name %><% end %><br/>
						        		Due Date: <%= task.duedate %><br/>
						        	<% end %>
					        	</description>
			        	</wordbox>
					  </div>
					</div>
				</div>
	    </div>
	<% end %>

app/views/tasks/edit.html.erb
<%= currently_at 'Tasks' %>

<div class="topbanner" style="font-weight:bold;margin-bottom:20px">
  Edit the Task
</div>

<div style="margin:auto;width:50%">
	<%= render 'form' %>
</div>

app/views/tasks/index.html.erb
<%= currently_at 'Tasks' %>

<div class="topstatement">
	<% if member_signed_in? %>
		<% if @tasks == 0 %>
		Looks like we should add a few tasks, click the button below
		<% end %>
	<% else %>
		Below are actual tasks created and used by current members, become a member and create your own.  
	<% end %>
</div>

<div class="topbanner">
    <% if member_signed_in? %>
        <%= link_to 'Add New Task', new_task_path, :method => 'get', :class => 'button-link' %>
    <% else %>
        <%= link_to 'Become a Member and Create Your Own', new_member_registration_path, :class => 'button-link' %>
    <% end %>
</div>

<%= render 'opentasktiles' %>

<div class="box">
			<div style="height:250px;width:250px;margin:0 25px"/>
				<script type="text/javascript"><!--
				google_ad_client = "ca-pub-5451064655705220";
				/* block */
				google_ad_slot = "3023406262";
				google_ad_width = 250;
				google_ad_height = 250;
				//-->
				</script>
				<script type="text/javascript"
				src="//pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</div>

<%= render 'closedtasktiles' %>

<div class="box">
			<div style="height:250px;width:250px;margin:0 25px"/>
				<script type="text/javascript"><!--
				google_ad_client = "ca-pub-5451064655705220";
				/* block */
				google_ad_slot = "3023406262";
				google_ad_width = 250;
				google_ad_height = 250;
				//-->
				</script>
				<script type="text/javascript"
				src="//pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</div>

app/views/tasks/new.html.erb
<%= currently_at 'Tasks' %>

<div class="topbanner" style="font-weight:bold;margin-bottom:20px">
  Add a New Task
</div>

<div style="margin:auto;width:50%">
	<%= render 'form' %>
</div>

app/views/tasks/show.html.erb
<%= currently_at 'Tasks' %>

<p id="notice"><%= notice %></p>

<p>
  <b>Member:</b>
  <%= @task.member_id %>
</p>

<p>
  <b>Goal:</b>
  <%= @task.goal_id %>
</p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Duedate:</b>
  <%= @task.duedate %>
</p>

<p>
  <b>Achievedate:</b>
  <%= @task.achievedate %>
</p>

<p>
  <b>Date:</b>
  <%= @task.date %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>