config/routes.rb
Successpath::Application.routes.draw do
  
  devise_for :members, :controllers => { :registrations => "registrations" }

  scope '/admin' do
    resources :members
  end

  get "pages/home"

  get "pages/contact"

  resources :affirmations

  resources :goals do
    member do
      get 'achieved'
    end
  end

  resources :tasks do
    member do
      get 'achieved'
    end
  end

  resources :users

  root :to => "pages#home"
  

end

app/views/pages/_action.html.erb
<div class="box">
	<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
		<div class="flipper">
		  <div class="front" style="background:black;color:white;text-align:center;font-size:1.5em;">
		    <div class="sectiontitle">
				<% if @member.actiontitle? %>
					<%= @member.actiontitle %>
				<% else %>
				Action!
				<% end %>
			</div>
		  </div>
		  <div class="back">
        <div class="wordbox-padding">
		    <wordbox>
	        		<description>
	        			<div class="quote">
							"<%= @member.actionquote %>"
						</div>
	        		</description>
        	</wordbox>
        </div>
		  </div>
		</div>
	</div>
</div>

app/views/pages/_assets.html.erb
<div class="box">
	<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
		<div class="flipper">
		  <div class="front" style="background:orange;color:white;text-align:center;font-size:1.5em">
		    <div class="sectiontitle" style="color:white">
				Net Worth Goal<br/>
				<description style="color:white"><%= number_to_currency(@member.desiredassets) %></description>
			</div>
		  </div>
		  <div class="back">
        <div class="wordbox-padding">
		    <wordbox>
	        		<description>
	        			<div class="quote">
	        				Desired: <%= number_to_currency(@member.desiredassets) %><br/>
	        				Actual: <%= number_to_currency(@member.actualassets) %>
						</div>
	        		</description>
        	</wordbox>
        </div>
		  </div>
		</div>
	</div>
</div>

app/views/pages/_cashflow.html.erb
<div class="box">
	<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
		<div class="flipper">
		  <div class="front" style="background:#31b7ea;color:white;text-align:center;font-size:1.5em">
		    <div class="sectiontitle" style="color:white">
				CashFlow Goal<br/>
				<description style="color:white"><%= number_to_currency(@member.desiredcf) %></description>
			</div>
		  </div>
		  <div class="back">
        <div class="wordbox-padding">
		    <wordbox>
    			<div class="quote">
    				Desired: <%= number_to_currency(@member.desiredcf) %><br/>
    				Actual: <%= number_to_currency(@member.actualcf) %>
				</div>
        	</wordbox>
        </div>
		  </div>
		</div>
	</div>
</div>

app/views/pages/_gettingthere.html.erb
<div class="sectionsquare">
		<div style="float:right"><%= button_to "Edit", edit_member_registration_path(@member), :method => 'get', :class => 'button' %></div>
		<div class="sectiontitle"><%= @member.actiontitle %></div>
	<div class="quote">
		"<%= @member.actionquote %>"
	</div>
</div>
<div style="clear:both"></div>

app/views/pages/_hometiles.html.erb
<div class="box">
	<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
		<div class="flipper">
		  <div class="front" style="background:black">
		  	<div class="sectiontitle" style="color:white">
		    	What Is It?
		    </div>
		  </div>
		  <div class="back">
        <div class="wordbox-padding">
		    <wordbox>
        		<name>What Is It?</name><br/>
	        		<description>
	        			Successpath.me is geared for people that want to change themselves...and ultimately
	        			change their life.  It is designed to be a straightforward quick method to review goals and
	        			affirmations on a daily basis - allowing you a simple push each day to meet them.
	        		</description>
        	</wordbox>
        </div>
		  </div>
		</div>
	</div>
</div>
<div class="box">
	<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
		<div class="flipper">
		  <div class="front" style="background:orange">
		    <div class="sectiontitle" style="color:white">How Does It Work?</div>
		  </div>
		  <div class="back">
        <div class="wordbox-padding">
		    <wordbox>
        		<name>How Does It Work?</name><br/>
	        		<description>
	        			That's up to you.  You simply add the goals you want to achieve in the goals tab, then add 
	        			some tasks to accomplish them.  Then add some personal affirmations to help you rewire the 
	        			way you look at things...then look at them each	day.
	        		</description>
        	</wordbox>
        </div>
		  </div>
		</div>
	</div>
</div>
<div class="box">
	<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
		<div class="flipper">
		  <div class="front">
		    <iframe width="305" height="250" src="//www.youtube.com/embed/hzBCI13rJmA?rel=0" frameborder="0" allowfullscreen></iframe>
		  </div>
		  <div class="back">
        <div class="wordbox-padding">
		    <wordbox>
        		<name>Add Your Motivational Videos</name><br/>
	        		<description>
	        			Flip back over and watch this video some more.
	        		</description>
        	</wordbox>
        </div>
		  </div>
		</div>
	</div>
</div>
<div class="box">
	<div style="height:250px;width:250px;margin:0 25px"/>
		<script type="text/javascript"><!--
		google_ad_client = "ca-pub-5451064655705220";
		/* block */
		google_ad_slot = "3023406262";
		google_ad_width = 250;
		google_ad_height = 250;
		//-->
		</script>
		<script type="text/javascript"
		src="//pagead2.googlesyndication.com/pagead/show_ads.js">
		</script>
	</div>
</div>
<div class="box">
	<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
		<div class="flipper">
		  <div class="front">
		    <div class="flexslider" style="width:300px">
			  <ul class="slides">
			    <% @affirmations.each do |affirmation| %>
			      <li style="padding:85px 0;font-size:1.5em;line-height:.9em;font-weight:normal">
			        <%= affirmation.title %>
			      </li>
			    <% end %>
			  </ul>
			</div>
		  </div>
		  <div class="back">
        <div class="wordbox-padding">
		    <wordbox>
        		<name>Create Your Own Affirmations</name><br/>
	        		<description>
	        			Flip back over and see recent real affirmations created by our members!
	        		</description>
        	</wordbox>
        </div>
		  </div>
		</div>
	</div>
</div>
<div class="box">
	<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
		<div class="flipper">
		  <div class="front" style="background:#31b7ea">
		    <div class="sectiontitle" style="color:white">How Much?</div>
		  </div>
		  <div class="back">
        <div class="wordbox-padding">
		    <wordbox>
        		<name>How Much?</name><br/>
	        		<description>
	        			Free.  Yesserie Bob.
	        		</description>
        	</wordbox>
        </div>
		  </div>
		</div>
	</div>
</div>
<div class="box">
	<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
		<div class="flipper">
		  <div class="front" style="background:black">
		    <div class="sectiontitle" style="color:white">How Do I Start?</div>
		  </div>
		  <div class="back">
        <div class="wordbox-padding">
		    <wordbox>
        		<name>How Do I Start?</name><br/>
	        		<description>
	        			You can become a member by clicking <%= link_to 'HERE', new_member_registration_path %>.
	        		</description>
        	</wordbox>
        </div>
		  </div>
		</div>
	</div>
</div>


<%= render 'goals/goaltiles_next30' %>

<div class="box">
	<div style="height:250px;width:250px;margin:0 25px"/>
		<script type="text/javascript"><!--
		google_ad_client = "ca-pub-5451064655705220";
		/* block */
		google_ad_slot = "3023406262";
		google_ad_width = 250;
		google_ad_height = 250;
		//-->
		</script>
		<script type="text/javascript"
		src="//pagead2.googlesyndication.com/pagead/show_ads.js">
		</script>
	</div>
</div>

app/views/pages/_ideal_life.html.erb
<div class="sectionsquare">
		<div style="float:right"><%= button_to "Edit", edit_member_registration_path(@member), :class => 'button', :method => 'get' %></div>
		<div class="sectiontitle">
			<% if @member.mainlifetitle? %>
				<%= @member.mainlifetitle %>
			<% else %>
			Life Statement
			<% end %>
		</div>
	<div class="quote">
		"<%= @member.mainlifequote %>"
	</div>
</div>
<div style="clear:both"></div>

app/views/pages/_ideal_life2.html.erb
<div class="box">
	<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
		<div class="flipper">
		  <div class="front" style="background:black;color:white;text-align:center;font-size:1.5em">
		    <div class="sectiontitle">
			<% if @member.mainlifetitle? %>
				<%= @member.mainlifetitle %>
			<% else %>
			Life Statement
			<% end %>
		</div>
		  </div>
		  <div class="back">
        <div class="wordbox-padding">
		    <wordbox>
	        		<description>
	        			<div class="quote">
							"<%= @member.mainlifequote %>"
						</div>
	        		</description>
        	</wordbox>
        </div>
		  </div>
		</div>
	</div>
</div>

app/views/pages/_networth.html.erb
<div class="sectionsquare">
	<div style="float:right"><%= button_to "Edit", edit_member_registration_path(@member), :method => 'get', :class => 'button' %></div>
	<div class="sectiontitle">Personal Financial Statement</div>
	<div class="quote">
		"<%= @member.financialstatementquote %>"
	</div>
	<table width="100%">
		<tr>
			<td colspan="2" style="width:50%;text-align:center;font-size:1em">Assets</td>
			<td colspan="2" style="text-align:center;font-size:1em">Monthly Cash Flow</td>
		</tr>
		<tr>
			<td style="width:25%;text-align:center;background:gray;color:white">Desired</td>
			<td style="width:25%;text-align:center;background:gray;color:white">Actual</td>
			<td style="width:25%;text-align:center;background:gray;color:white">Desired</td>
			<td style="text-align:center;background:gray;color:white">Actual</td>
		</tr>
		<tr style="font-size:1.2em">
			<td style="font-size:.8em;text-align:center;padding:5px"><%= number_to_currency(@member.desiredassets) %></td>
			<td style="font-size:.8em;text-align:center;padding:5px"><%= number_to_currency(@member.actualassets) %></td>
			<td style="font-size:.8em;text-align:center;padding:5px"><%= number_to_currency(@member.desiredcf) %></td>
			<td style="font-size:.8em;text-align:center;padding:5px"><%= number_to_currency(@member.actualcf) %></td>
		</tr>
	</table>

</div>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<% currently_at 'Home' %>

	<% if member_signed_in? %>
	
	<% if notice %>
		<div id="notice" style="z-index:2">
			<%= notice %>
		</div>
	<% end %>

	<% if alert %>
	    <div id="alert" style="z-index:2">
	      <%= alert %>
	    </div>
	  <% end %>
	  
	<div class="topstatement">
		<% if @member.mainlifetitle == nil %>
			Now it's time to get started!  This page is designed to bring front and center; your high level objectives (top colored squares), your immediate tasks and closest goals.  But since you just joined, we have a bare cupboard.<br/><br/>
			So first thing, let's give these squares below your personal touch. Here's to your success!
		<% elsif @goals.empty? %>
			Looks like we could benefit from adding some goals, <%= link_to 'Click Here to Start', new_goal_path, :class => 'button-link' %>
		<% elsif @affirmations.empty? %>
			Looks like we could benefit from adding some affirmations, <%= link_to 'Click Here to Start Adding Them', new_affirmation_path, :class => 'button-link' %>
		<% elsif @goals.size == 1 %>
			Really?  One goal? You're better than that! <%= link_to 'Click Here to Add Another!', new_goal_path, :class => 'button-link' %>
		<% else %>
		Great to have you back!  Let's meet some more goals!  Push yourself!  Focus on the big goals.
		<% end %>	
	</div>

	<div class="topbanner">
		<%= link_to 'Edit Your Squares', edit_member_registration_path(@member), :method => 'get', :class => 'button-link' %>
		<%= link_to 'New Goal', new_goal_path, :method => 'get', :class => 'button-link' %>
		<%= link_to 'New Task', new_task_path, :method => 'get', :class => 'button-link' %>
		<%= link_to 'New Affirmation', new_affirmation_path, :method => 'get', :class => 'button-link' %>
	</div>
		<%= render 'ideal_life2' %>
		<%= render 'assets' %>
		<%= render 'cashflow' %>
		<%= render 'action' %>
		<div class="box">
			<div align="center" style="vertical-align:middle;diplay:inline-block">
				<script type="text/javascript"><!--
				google_ad_client = "ca-pub-5451064655705220";
				/* block */
				google_ad_slot = "3023406262";
				google_ad_width = 250;
				google_ad_height = 250;
				//-->
				</script>
				<script type="text/javascript"
				src="//pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</div>
		<%= render 'tasks/opentasktiles' %>
		<div class="box">
			<div align="center" style="vertical-align:middle;diplay:inline-block">
				<script type="text/javascript"><!--
				google_ad_client = "ca-pub-5451064655705220";
				/* block */
				google_ad_slot = "3023406262";
				google_ad_width = 250;
				google_ad_height = 250;
				//-->
				</script>
				<script type="text/javascript"
				src="//pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</div>
		<%= render 'goals/goals_nodate' %>
		<%= render 'goals/goaltiles_next30' %>
	<% else %>
	<div class="topbanner">
		<%= link_to 'Sign In', new_member_session_path, :method => 'get', :class => 'button-link' %>
		<%= link_to 'Become a Member', new_member_registration_path, :method => 'get', :class => 'button-link' %> 
	</div>
		<%= render 'hometiles' %>
	<% end %>