config/routes.rb
Successpath::Application.routes.draw do
  
  devise_for :members, :controllers => { :registrations => "registrations" }

  scope '/admin' do
    resources :members
  end

  get "pages/home"

  get "pages/contact"

  resources :affirmations

  resources :goals do
    member do
      get 'achieved'
    end
  end

  resources :tasks do
    member do
      get 'achieved'
    end
  end

  resources :users

  root :to => "pages#home"
  

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :description, :goaldate, :image, :name, :priority, :url, :user_id, :achievedate, :progress

  belongs_to :member
  has_many :tasks, :dependent => :destroy

  accepts_nested_attributes_for :tasks, :member
  
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  # GET /goals
  # GET /goals.json

  def achieved
    @goal = Goal.find(params[:id])

    respond_to do |format|
      @goal.achievedate = Date.today
      @goal.save
      format.html {redirect_to goals_path}
      format.json
    end

  end


  def index
    if member_signed_in?
      @goals_nodate = Goal.where("member_id = ? and goaldate is ?", current_member, nil)
      @goals_next30 = Goal.where("member_id = ? and achievedate is ? and goaldate >= ? and goaldate <= ?", current_member, nil, Date.today, Date.today + 30).order("goaldate ASC")
      @goals_future = Goal.where("member_id = ? and achievedate is ? and goaldate > ?", current_member, nil, Date.today + 30).order("goaldate ASC")
      @goals_past = Goal.where("member_id = ? and goaldate < ?", current_member, Date.today)
    else
      @goals_nodate = Goal.where("goaldate is ?", nil).limit(3)
      @goals_next30 = Goal.where("achievedate is ? and goaldate >= ? and goaldate <= ?", nil, Date.today, Date.today + 30).limit(10)
      @goals_future = Goal.where("achievedate is ? and goaldate > ?", nil, Date.today + 30).limit(10)
      @goals_past = Goal.where("goaldate < ?", Date.today).limit(2)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @goals }
    end
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    @goal = Goal.find(params[:id])
    @opentasks = Task.where("goal_id = ? and achievedate is ?", @goal.id, nil).order("duedate ASC")
    @closedtasks = Task.where("goal_id = ? and achievedate is not ?", @goal.id, nil)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @goal }
    end
  end

  # GET /goals/new
  # GET /goals/new.json
  def new
    @goal = Goal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @goal }
    end
  end

  # GET /goals/1/edit
  def edit
    @goal = Goal.find(params[:id])
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = current_member.goals.build(params[:goal])

    respond_to do |format|
      if @goal.save
        format.html { redirect_to goals_path, notice: 'Goal was successfully created.' }
        format.json { render json: @goal, status: :created, location: @goal }
      else
        format.html { render action: "new" }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /goals/1
  # PUT /goals/1.json
  def update
    @goal = Goal.find(params[:id])

    respond_to do |format|
      if @goal.update_attributes(params[:goal])
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy

    respond_to do |format|
      format.html { redirect_to goals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="goalform">
  <div class="inputbox" style="background:#e9e9e9;border-radius:5px;border:2px dashed gray;margin-right:10px">
    <% if @goal.image? %>
    <div style="width:250px">
      <%= image_tag(@goal.image, :size => '350x280') %><br/>
        Current Picture<br/><br/>
          Change your picture: <%= f.text_area :image, size:"35x4", style:"font-size:.8em" %>
    </div>
    <% else %>
    <div class="field">
      Add a Picture<br/><br/>
      1. Find a picture on the web<br/>
      2. Right click and copy the "url"<br/>
      3. Then paste in the box below:<br/>
      <%= f.text_area :image, size:"35x4", style:"font-size:.8em", :class => 'inputfield' %>
    </div>
    <% end %>
  </div>
</div>
<div class="goalform">
  <div class="inputbox">
    <div class="field">
      Name of Goal<br />
      <%= f.text_field :name, :class => 'inputfield', :required => true %>
    </div>
    <div class="field">
      Addt'l Comments:<br />
      <%= f.text_area :description, size:"35x4", :class => 'inputfield' %>
    </div>
    <div class="field">
      <%= f.label :goaldate %><br />
      <%= f.text_field :goaldate, :class => 'datepicker' %>
    </div>
    <div class="field">
      <%= f.label :progress %><br />
      <%= f.number_field :progress, :class => 'inputfield' %>
    </div>
    <div class="actions">
      <%= f.submit "Save!", :class => 'button-link', :style => 'font-size:1.1em' %> <%= link_to 'Cancel', goals_path, :class => 'description' %>
    </div>
  </div>
</div>

<% end %>

app/views/goals/_goals_nodate.html.erb
<% if @goals_nodate.present? %>
	<% @goals_nodate.each do |goal| %>
		<div class="box">
				<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
					<div class="flipper">
					  <div class="front" style="background:black">
					  	<% if goal.image? %>
					    	<%= image_tag(goal.image) %>
					    	<% if goal.goaldate %>
					    	<div class="title"><%= number_to_percentage(goal.progress, precision: 0) %> and <%= distance_of_time_in_words(Time.now,goal.goaldate) %> left to achieve</div>
					    	<% end %>
					    <% else %>
					    	<div class="sectiontitle"><%= goal.name %></div>
					    <% end %>
					  </div>
					  <div class="back">
              <div class="wordbox-padding">
					    <wordbox>
			        		<name><%= goal.name %></name><br/>
			        		<% if member_signed_in? %>
				        		<description>
				        			<%= link_to 'Edit', edit_goal_path(goal) %> | <%= link_to 'Delete', goal, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Show Details', goal %><br/><br/>
				        			<%= goal.description %><br/><br/>
				        			Target Date: <%= goal.goaldate %><br/>
				        		</description>
			        		<% else %>
			        			<description>
			        			</description>
			        		<% end %>
			        	</wordbox>
              </div>
					  </div>
					</div>
				</div>
	        </div>
	<% end %>
<% end %>

app/views/goals/_goals_past.html.erb
<% if @goals_past.present? %>
	<% @goals_past.each do |goal| %>
		<div class="box">
				<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
					<div class="flipper">
					  <div class="front" style="background:black">
					  	<% if goal.image? %>
					    	<%= image_tag(goal.image) %>
					    <% else %>
					    	<div class="sectiontitle"><%= goal.name %></div>
					    <% end %>
					  </div>
					  <div class="back">
              <div class="wordbox-padding">
					    <wordbox>
			        		<name><%= goal.name %></name><br/>
			        		<% if member_signed_in? %>
				        		<description>
				        			<%= link_to 'Edit', edit_goal_path(goal) %> | <%= link_to 'Delete', goal, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Show Details', goal %><br/><br/>
				        			<%= goal.description %><br/><br/>
				        			Target Date: <%= goal.goaldate.strftime('%m/%d/%Y') %><br/>
				        		</description>
			        		<% else %>
			        			<description>
			        				<% if goal.goaldate %>
			        				Created <%= distance_of_time_in_words(Time.now,goal.created_at) %> ago
			        				<% end %>
			        			</description>
			        		<% end %>
			        	</wordbox>
              </div>
					  </div>
					</div>
				</div>
	        </div>
	<% end %>
<% end %>

app/views/goals/_goaltiles.html.erb
<% @goals.each do |goal| %>
		<div class="box">
			<% if goal.image? %>
				<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
					<div class="flipper">
					  <div class="front">
					    <%= link_to image_tag(goal.image), goal %>
					    <div class="title"><%= number_to_percentage(goal.progress, precision: 0) %> and <%= distance_of_time_in_words(Time.now,goal.goaldate) %> left to achieve</div>
					  </div>
					  <div class="back">
					    <wordbox>
			        		<name><%= goal.name %></name><br/>
			        		<% if member_signed_in? %>
				        		<description>
				        			<%= link_to 'Edit', edit_goal_path(goal) %> | <%= link_to 'Delete', goal, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Show Details', goal %><br/><br/>
				        			<%= goal.description %><br/><br/>
				        			Goal Data: <%= goal.goaldate %><br/>
				        		</description>
			        		<% else %>
			        			<description>
			        				<%= distance_of_time_in_words(Time.now,goal.goaldate) %> left to achieve it<br/>
			        				Created <%= distance_of_time_in_words(Time.now,goal.created_at) %> ago
			        			</description>
			        		<% end %>
			        	</wordbox>
					  </div>
					</div>
				</div>
	        <% else %>
	        	<wordbox>
	        		<name><%= goal.name %></name><br/>
	        		<description>
	        			<% if member_signed_in? %>
	        			<%= goal.description %><br/>
	        			<%= goal.goaldate %><br/>
		        			<%= link_to 'Edit', edit_goal_path(goal) %> | 
		        			<%= link_to 'Delete', goal, method: :delete, data: { confirm: 'Are you sure?' } %> |
		        			<%= link_to 'Achieved', achieved_goal_path(goal) %>
		        		<% else %>
	        				<%= distance_of_time_in_words(Time.now,goal.goaldate) %> left to achieve it<br/>
	        				Created <%= distance_of_time_in_words(Time.now,goal.created_at) %> ago
		        		<% end %>
	        		</description>
	        	</wordbox>
	        <% end %>
	    </div>
	<% end %>

app/views/goals/_goaltiles_future.html.erb
<% if @goals_nodate.present? %>
<% @goals_future.each do |goal| %>
		<div class="box">
				<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
					<div class="flipper">
					  <div class="front" style="background:black">
					  	<% if goal.image? %>
					    	<%= image_tag(goal.image) %>
					    <% else %>
					    	<div class="sectiontitle"><%= goal.name %></div>
					    <% end %>
					  </div>
					  <div class="back">
              <div class="wordbox-padding">
					    <wordbox>
			        		<name><%= goal.name %></name><br/>
			        		<% if member_signed_in? %>
				        		<description>
				        			<%= link_to 'Edit', edit_goal_path(goal) %> | <%= link_to 'Delete', goal, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Show Details', goal %><br/><br/>
				        			<%= goal.description %><br/><br/>
				        			Target Date: <%= goal.goaldate.strftime('%m/%d/%Y') %><br/>
				        		</description>
			        		<% else %>
			        			<description>
			        				<% if goal.goaldate %>
			        				<%= distance_of_time_in_words(Time.now,goal.goaldate) %> left to achieve it<br/>
			        				Created <%= distance_of_time_in_words(Time.now,goal.created_at) %> ago
			        				<% end %>
			        			</description>
			        		<% end %>
			        	</wordbox>
              </div>
					  </div>
					</div>
				</div>
	        </div>
	<% end %>
<% end %>

app/views/goals/_goaltiles_next30.html.erb
<% @goals_next30.each do |goal| %>
		<div class="box">
				<div class="flip-container" ontouchstart="this.classList.toggle('hover')">
					<div class="flipper">
					  <div class="front" style="background:black">
					    <% if goal.image? %>
					    	<%= image_tag(goal.image) %>
					    <% else %>
					    	<div class="sectiontitle"><%= goal.name %></div>
					    <% end %>
					  </div>
					  <div class="back">
              <div class="wordbox-padding">
					    <wordbox>
			        		<name><%= goal.name %></name><br/>
			        		<% if member_signed_in? %>
				        		<description>
				        			<%= link_to 'Edit', edit_goal_path(goal) %> | <%= link_to 'Delete', goal, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Show Details', goal %> | <%= link_to 'Achieved!', achieved_goal_path(goal) %><br/><br/>
				        			<%= goal.description %><br/><br/>
				        			Target Date: <%= goal.goaldate.strftime('%m/%d/%Y') %><br/>
				        		</description>
			        		<% else %>
			        			<description>
			        				<% if goal.goaldate %>
			        					<%= distance_of_time_in_words(Time.now,goal.goaldate) %> left to achieve it<br/>
			        					Created <%= distance_of_time_in_words(Time.now,goal.created_at) %> ago
			        				<% end %>
			        			</description>
			        		<% end %>
			        	</wordbox>
              </div>
					  </div>
					</div>
				</div>
	    </div>
	<% end %>

app/views/goals/edit.html.erb
<% currently_at 'Goals' %>

<div class="topbanner" style="margin-bottom:20px">
  Editing the <%= @goal.name %> Goal
</div>

<%= render 'form' %>

app/views/goals/index.html.erb
<% currently_at 'Goals'%>

<div class="topstatement">
	<% if member_signed_in? %>
		<% if @goals_next30 == 0 || @goals_future == 0 %>
		Looks like we should add a few goals, click the button below.
		<% else %>
		Making progress - awesome!  Think big! FEEL these things in your life!  Remember to review them every day.
		<% end %>
	<% else %>
		Below are actual goals created and used by current members, become a member and create your own.  You can put whatever you want - think of this as your visionboard.  Put whatever is going to motivate you each day - and look at it each day.  Become a member today!
	<% end %>
</div>

<div class="topbanner">
	<% if member_signed_in? %>
		<%= link_to 'Add New Goal', new_goal_path, :method => 'get', :class => 'button-link' %>
	<% else %>
		<%= link_to 'Become a Member and Create Your Own', new_member_registration_path, :class => "button-link" %>
	<% end %>
</div>

<div class="container">

	<% if @goals_next30 == 0 %>
	<div class="box">
		<iframe width="300" height="250" src="//www.youtube.com/embed/wvvbcVxA5Y4?autoplay=1&rel=0"></iframe>
	</div>
	<% end %>

	<%= render 'goaltiles_next30' %>

	<div class="box">
		<div align="center" style="vertical-align:middle">
			<script type="text/javascript"><!--
			google_ad_client = "ca-pub-5451064655705220";
			/* block */
			google_ad_slot = "3023406262";
			google_ad_width = 250;
			google_ad_height = 250;
			//-->
			</script>
			<script type="text/javascript"
			src="//pagead2.googlesyndication.com/pagead/show_ads.js">
			</script>
		</div>
	</div>

	<%= render 'goaltiles_future' %>

	<div class="box">
		<div align="center" style="vertical-align:middle;diplay:inline-block">
			<script type="text/javascript"><!--
			google_ad_client = "ca-pub-5451064655705220";
			/* block */
			google_ad_slot = "3023406262";
			google_ad_width = 250;
			google_ad_height = 250;
			//-->
			</script>
			<script type="text/javascript"
			src="//pagead2.googlesyndication.com/pagead/show_ads.js">
			</script>
		</div>
	</div>	

	<%= render 'goals_past' %>

  <%= render 'goals_nodate' %>
		
</div>

app/views/goals/new.html.erb
<% currently_at 'Goals' %>

<div class="topbanner" style="margin-bottom:20px;font-weight:bold">
  Add a New Goal
</div>

<%= render 'form' %>

app/views/goals/oldindex.html.erb
<% currently_at 'Goals' %>

<h1>My Goals</h1>
<%= link_to 'New Goal', new_goal_path %>


<table width="100%">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Description</th>
    <th>Goaldate</th>
    <th>Image</th>
    <th>Url</th>
    <th>Priority</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @goals.each do |goal| %>
  <tr>
    <td width="300px">
        <% if goal.image? %>
        <%= link_to image_tag(goal.image), goal.url %>
        <% end %>
    </td>
    <td><%= goal.name %></td>
    <td><%= goal.description %></td>
    <td><%= goal.goaldate %></td>
    <td><%= goal.priority %></td>
    <td><%= link_to 'Show', goal %></td>
    <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
    <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/goals/show.html.erb
<%= currently_at 'Goals' %>

<p id="notice"><%= notice %></p>
<div class="topbanner" style="margin:10px 0">
     <%= link_to 'Add New Task', new_task_path(:goal => @goal.id), :method => 'get', :class => 'button-link' %>
  </div>

<div class="showpicturebox" >
  <% if @goal.image? %>
    <%= image_tag(@goal.image) %>
  <% else %>
    <div style="background:#e9e9e9;height:200px;width:100%;padding-top:60px;text-align:center">
      No Image Selected Yet
    </div>
  <% end %> 
</div>

<div class="showtopinfobanner">
  <div style="float:left">
  <name style="font-size:1.75em;font-weight:bold">
    <%= @goal.name %> 
  </name>
    <div>
      <description style="padding-left:10px">
        <%= @goal.description %>
      </description>
    </div>
  </div>
  <div style="float:right">
  <%= link_to 'Edit', edit_goal_path(@goal) %> | <%= link_to 'Back', goals_path %> | <%= link_to 'Achieved!', achieved_goal_path(@goal) %>
    <div style="padding-top:10px;font-size:1.25em">Target Date: <% if @goal.goaldate.present? %><%= @goal.goaldate.strftime('%m/%d/%Y') %><% else %>None Selected<% end %></div>
  </div>
</div>

<div style="clear:both"/>

<div style="height:90px;width:970px;position:relative;margin-left:-10px"/>
      <script type="text/javascript"><!--
      google_ad_client = "ca-pub-5451064655705220";
      /* Large Horizontal - Goal Detail */
      google_ad_slot = "7754657066";
      google_ad_width = 970;
      google_ad_height = 90;
      //-->
      </script>
      <script type="text/javascript"
      src="//pagead2.googlesyndication.com/pagead/show_ads.js">
      </script>
    </div>

<div>

  

<%= render 'tasks/opentasktiles' %>

<div style="clear:both">
  <hr/>

<%= render 'tasks/closedtasktiles' %>

</div>