config/routes.rb
Successpath::Application.routes.draw do
  
  devise_for :members, :controllers => { :registrations => "registrations" }

  scope '/admin' do
    resources :members
  end

  get "pages/home"

  get "pages/contact"

  resources :affirmations

  resources :goals do
    member do
      get 'achieved'
    end
  end

  resources :tasks do
    member do
      get 'achieved'
    end
  end

  resources :users

  root :to => "pages#home"
  

end

app/views/layouts/_header.html.erb
<section id="regular_header">
	<div class="header">

		<div class="headerstandard">
			<%= link_to image_tag("Logo.png", size:"400x70"), root_path %>
		</div>
		<div class="headerright">
			<nav id="utility" style="text-align:right;font-size:.8em;padding:5px 20px 0 0">
			    <% if member_signed_in? %>
			    	<%= link_to current_member.email, edit_member_registration_path %> | <%= link_to "Sign Out", destroy_member_session_path, :method => :delete %> |
				    <% if current_member.admin? %>
				    	<%= link_to 'Admin', members_path %>
				    <% else %>
				    	<%= link_to 'Help', 'mailto:dedkins@edkinsgroup.com?subject=Help with SuccessPath Please' %>
				    <% end %>
			    <% else %>
			    	<%= link_to "Sign In", new_member_session_path %> | 
			    	<%= link_to "Sign Up", new_member_registration_path %> |
			    	<%= link_to "Help", 'mailto:dedkins@edkinsgroup.com?subject=Help with SuccessPath Please' %>
			    <% end %>
			</nav>
			<%= yield :main_navigation %>
		</div>

	</div>
</section>
<section id="mobile_header">
		<div class="headermobile">
			<%= link_to image_tag("Logo.png", size:"300x50"), root_path %>
		</div>

		<div class="headerright">
			<%= yield :main_navigation %>
		</div>

</section>

<section id="iphone_header">
		<div class="headeriphone">
			<%= link_to image_tag("Logo.png", size:"450x80"), root_path %>
		</div>

		<div class="headerright">
			<%= yield :main_navigation %>
		</div>
</section>

app/views/layouts/_main_nav.html.erb
<% content_for :main_navigation do %>

	<nav id="main_nav" role="navigation">
	  <ul>
	    <%= nav_tab 'Home', pages_home_path, current: current_tab %>
	    <%= nav_tab 'Goals', goals_path, current: current_tab %>
	    <%= nav_tab 'Tasks', tasks_path, current: current_tab %>
	    <%= nav_tab 'Affirmations', affirmations_path, current: current_tab%>
	  </ul>
	 </nav>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Successpath!</title>
  <!-- Place this data between the <head> tags of your website -->
  <meta name="description" content="Successpath is built to help people focus on improving their life through daily intention.
                                    Set up your visionboard of goals with target dates, add some personal affirmations, sprinkle
                                    in your mission and action statements, finish with net worth and cashflow goals - review daily 
                                    - and see how things start changing for you." />

  <!-- Twitter Card data -->
  <meta name="twitter:card" value="summary">

  <!-- Open Graph data -->
  <meta property="og:title" content="Successpath!" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="http://www.successpath.me/" />
  <meta property="og:image" content="http://successpath.me/assets/Logo.png" />
  <meta property="og:description" content="Successpath is built to help people focus on improving their life through daily intention.
                                    Set up your visionboard of goals with target dates, add some personal affirmations, sprinkle
                                    in your mission and action statements, finish with net worth and cashflow goals - review daily 
                                    - and see how things start changing for you." />
  
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato:300">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta content="True" name="HandheldFriendly">
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" type="text/css" media="screen" href="http://www.devslide.com/public/labs/browser-detection/browser-detection.css" />
  <script type="text/javascript" src="http://www.devslide.com/public/labs/browser-detection/browser-detection.js">
  <script type="text/javascript">
  <!--
  var displayPoweredBy = false;
  var notSupportedBrowsers = [{'os': 'Any', 'browser': 'MSIE', 'version': 10}];
  var noticeLangCustom = {
  "title": "Certain Features May Not Be Viewable",
  "notice": "We use a newer website technology that flips items over - some browsers (especially Microsoft) seem to have a challenge with it. One way to see if your browser supports this is to try to flip over any of the squares on this page. If hovering over them does not work, your browser is not supported. Try another. Thank you.",
  "selectBrowser": "If you wanted to try to update your browser, click one of the following icons",
  "remindMeLater": "Remind Me Later",
  "neverRemindAgain": "I Got It; Don't Remind Me Again!" };
  // -->
  </script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-16925588-12', 'successpath.me');
    ga('send', 'pageview');

  </script>

  <script type="text/javascript" charset="utf-8">
    $(window).load(function() {
      $('.flexslider').flexslider({
        animation: true,
        animationSpeed: 600,
        directionNav: true,
        touch: true, 
        animation: "slide",
        slideshowSpeed: 3500,
      });
    });
  </script>

</head>
<body>
<div class="container">
  <div class="header">
    <%= render 'layouts/header' %>
  </div>
  <div class="yield">
    
    <%= yield %>

  </div>
  
</div>
<div class="clearfooter"></div>
<div class="footer">
    <% if member_signed_in? %>
      <%= link_to "Sign Out", destroy_member_session_path, :method => :delete, :class => 'button-link' %> 
    <% else %>
      <%= link_to 'Sign-In!', new_member_session_path, :class => 'button-link' %> <%= link_to "Become a Member", new_member_registration_path, :class => 'button-link' %>
    <% end %>
    <%= link_to 'Help', 'mailto:dedkins@edkinsgroup.com?subject=Help with SuccessPath Please', :class => 'button-link' %> <br/><br/>
    Copyright 2016 | The Edkins Group, LLC
  </div>
</body>
</html>

app/views/layouts/member_mailer.html.erb
<html style="bgcolor:#e9e9e9">

<div style="border:15px solid #333333;padding:30px;margin:auto;width:80%">
	<div style="margin:10px 0">
		<%= image_tag("http://www.successpath.me/assets/Logo.png", :size => "320x60") %>
	<div>

	<%= yield %>


</div>

</html>